# Generated by Django 4.2.27 on 2025-12-11 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='band_score',
        ),
        migrations.AddField(
            model_name='user',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='english_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper Intermediate'), ('advanced', 'Advanced'), ('ielts_5', 'IELTS 5.0'), ('ielts_5.5', 'IELTS 5.5'), ('ielts_6', 'IELTS 6.0'), ('ielts_6.5', 'IELTS 6.5'), ('ielts_7', 'IELTS 7.0+'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='target_score',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_time_spent',
            field=models.IntegerField(default=0, help_text='Total time spent in minutes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('english', 'English'), ('math', 'Math')], max_length=20)),
                ('module', models.IntegerField(choices=[(1, 'Module 1'), (2, 'Module 2')])),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_answer', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['category', 'module', 'question_number'],
                'unique_together': {('category', 'module', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('break', 'Break'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('current_section', models.CharField(default='english', max_length=20)),
                ('current_module', models.IntegerField(default=1)),
                ('english_module1_score', models.IntegerField(default=0)),
                ('english_module2_score', models.IntegerField(default=0)),
                ('math_module1_score', models.IntegerField(default=0)),
                ('math_module2_score', models.IntegerField(default=0)),
                ('english_score', models.IntegerField(default=0)),
                ('math_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.examsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
            options={
                'db_table': 'exam_answers',
                'unique_together': {('exam_session', 'question')},
            },
        ),
    ]
