# Generated by Django 6.0 on 2025-12-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('math_module1', 'Math Module 1'), ('math_module2', 'Math Module 2')], max_length=20),
        ),
    ]
