# Generated by Django 6.0 on 2025-12-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_test_test_questions_alter_test_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_price', models.DecimalField(decimal_places=2, default=19999.0, help_text="Exam test narxi (so'm)", max_digits=10)),
                ('subscription_price', models.DecimalField(decimal_places=2, default=49999.0, help_text="Oylik subscription narxi (so'm)", max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pricing_settings',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('exam', 'Exam'), ('subscription', 'Subscription')], default='exam', max_length=20),
        ),
    ]
