# Generated by Django 5.2.9 on 2025-12-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pricingsettings_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='question_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='app.test'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question'),
        ),
    ]
