# Generated by Django 5.2.9 on 2025-12-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_examanswer_question_index_examsession_test_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='category',
            field=models.CharField(default='english', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('exam_session', 'question', 'question_index', 'category')},
        ),
    ]
