# Generated by Django 6.0 on 2025-12-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_examanswer_unique_together_examanswer_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('english_module1', 'English Module 1'), ('english_module2', 'English Module 2'), ('math_module1', 'Math Module 1'), ('math_module2', 'Math Module 2')], max_length=20),
        ),
    ]
