# Generated by Django 4.2.27 on 2025-12-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_band_score_user_best_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
